version: '3.8'

services:
  frontend:
    build:
      context: ./lfusys-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./lfusys-app/src:/app/src
      - /app/node_modules