name: lfusys-prod
services:
  gateway:
    container_name: lfusys-gateway-prod
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
      target: gateway-prod
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      sessions:
        condition: service_healthy
    healthcheck:
      test: ["CMD","wget","--no-verbose","--tries=1","--spider","http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 2s
      retries: 3
    networks:
      - lfusys
  sessions:
    container_name: lfusys-sessions-prod
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
      target: sessions-prod
    env_file:
      - .env.prod
    healthcheck:
      test: [ "CMD", "/bin/grpc_health_probe", "-addr=:50051" ]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
    networks:
      - lfusys

  uploads:
    container_name: lfusys-uploads-prod
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
      target: uploads-prod
    env_file:
      - .env.prod
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD","wget","--no-verbose","--tries=1","--spider","http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 2s
      retries: 3
    networks:
      - lfusys

  redis:
    image: redis:8-alpine
    container_name: lfusys-redis-prod
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 768M
    networks:
      - lfusys

  frontend:
    container_name: lfusys-frontend-prod
    build:
      context: ./frontend/lfusys-app/
      dockerfile: Dockerfile.prod
      args:
        VITE_GATEWAY_API_URL: http://localhost:8080/api/v1
        VITE_UPLOADS_API_URL: http://localhost:8081/api/v1
        VITE_GITHUB_CLIENT_ID: Ov23ligIk1n1MnNXDZWA
        VITE_GITHUB_REDIRECT_URI: http://localhost:8080/api/v1/auth/github/callback
        VITE_GOOGLE_CLIENT_ID: 441188855882-r9hj22sh2939r6nj0jnjn1mo8tkoua6q.apps.googleusercontent.com
        VITE_GOOGLE_REDIRECT_URI: http://localhost:8080/api/v1/auth/google/callback
    ports:
      - "80:8080"
    networks:
      - lfusys

networks:
  lfusys:
    driver: bridge

volumes:
  redis_data: