services:
  gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: gateway
    ports:
      - "8080:8080"
    env_file:
      - ./backend/services/gateway/.env
    depends_on:
      - jaeger
      - sessions
    volumes:
      - ./backend/services/gateway:/app/services/gateway
      - ./backend/services/commons:/app/services/commons

  sessions:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: sessions
    env_file:
      - ./backend/services/sessions/.env
    depends_on:
      - jaeger
    volumes:
      - ./backend/services/sessions:/app/services/sessions
      - ./backend/services/commons:/app/services/commons

  uploads:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: uploads
    env_file:
      - ./backend/services/uploads/.env
    depends_on:
      - jaeger
    ports:
      - "8081:8080" # only for testing
    volumes:
      - ./backend/services/uploads:/app/services/uploads
      - ./backend/services/commons:/app/services/commons

  frontend:
    build:
      context: ./frontend/lfusys-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/lfusys-app:/app
      - /app/node_modules

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly","yes"]

  # resources for testing
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sqs
      - AWS_DEFAULT_REGION=us-east-1


  # for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686" # UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
      - "6831:6831/udp" # legacy agent


volumes:
  redis_data: